SELECT 'S_BATCH' AS table_name, COUNT(*) AS row_count FROM LABVANTAGE.S_BATCH
UNION ALL
SELECT 'S_SAMPLE' AS table_name, COUNT(*) AS row_count FROM LABVANTAGE.S_SAMPLE
UNION ALL
SELECT 'SDIDATA' AS table_name, COUNT(*) AS row_count FROM LABVANTAGE.SDIDATA
UNION ALL
SELECT 'SDIDATAITEM' AS table_name, COUNT(*) AS row_count FROM LABVANTAGE.SDIDATAITEM;