SELECT 'PROD.CO_SAMPLE_TEST_LG' AS table_name, COUNT(*) AS row_count FROM PROD.CO_SAMPLE_TEST_LG cstl
UNION ALL
SELECT 'PROD.MM_MATERIAL_PLANT_SP' AS table_name, COUNT(*) AS row_count FROM PROD.MM_MATERIAL_PLANT_SP mmps
UNION ALL
SELECT 'PROD.PM_BATCH_ST' AS table_name, COUNT(*) AS row_count FROM PROD.PM_BATCH_ST pbs
UNION ALL
SELECT 'CSP_ADMIN.CSP_ACTIONS' AS table_name, COUNT(*) AS row_count FROM CSP_ADMIN.CSP_ACTIONS ca
UNION ALL
SELECT 'CSP_ADMIN.CSP_LIEN_PRODUITS_LOTS' AS table_name, COUNT(*) AS row_count FROM CSP_ADMIN.CSP_LIEN_PRODUITS_LOTS clpl
UNION ALL
SELECT 'CSP_ADMIN.CSP_VALEURS' AS table_name, COUNT(*) AS row_count FROM CSP_ADMIN.CSP_VALEURS cv2
UNION ALL
SELECT 'CSP_ADMIN.CSP_TYPE_CARACTERISTIQUES' AS table_name, COUNT(*) AS row_count FROM CSP_ADMIN.CSP_TYPE_CARACTERISTIQUES ctc;